version: "3.9"

services:
  task-service:
    build: .
    container_name: portfolio-service
    ports:
      - "8085:8080"
    environment:
      - DB_DIR=/var/data
    volumes:
      - ./data:/var/data